/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "coffee_machine.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RemoteApiRs232_ApiMessage, RemoteApiRs232_ApiMessage, 4)


PB_BIND(RemoteApiRs232_StartProduct, RemoteApiRs232_StartProduct, AUTO)


PB_BIND(RemoteApiRs232_CancelProduct, RemoteApiRs232_CancelProduct, AUTO)


PB_BIND(RemoteApiRs232_StartProductCategoryByName, RemoteApiRs232_StartProductCategoryByName, AUTO)


PB_BIND(RemoteApiRs232_GetProductList, RemoteApiRs232_GetProductList, AUTO)


PB_BIND(RemoteApiRs232_GetAvailableProductIds, RemoteApiRs232_GetAvailableProductIds, AUTO)


PB_BIND(RemoteApiRs232_GetActiveEvents, RemoteApiRs232_GetActiveEvents, AUTO)


PB_BIND(RemoteApiRs232_ForceRinse, RemoteApiRs232_ForceRinse, AUTO)


PB_BIND(RemoteApiRs232_PostponeRinse, RemoteApiRs232_PostponeRinse, AUTO)


PB_BIND(RemoteApiRs232_GetSwVersion, RemoteApiRs232_GetSwVersion, AUTO)


PB_BIND(RemoteApiRs232_ProductStarted, RemoteApiRs232_ProductStarted, AUTO)


PB_BIND(RemoteApiRs232_ProductCategoryByNameStarted, RemoteApiRs232_ProductCategoryByNameStarted, AUTO)


PB_BIND(RemoteApiRs232_ProductCancelled, RemoteApiRs232_ProductCancelled, AUTO)


PB_BIND(RemoteApiRs232_ProductList, RemoteApiRs232_ProductList, AUTO)


PB_BIND(RemoteApiRs232_ProductList_ProductListEntry, RemoteApiRs232_ProductList_ProductListEntry, AUTO)


PB_BIND(RemoteApiRs232_AvailableProductIds, RemoteApiRs232_AvailableProductIds, AUTO)


PB_BIND(RemoteApiRs232_ActiveEvents, RemoteApiRs232_ActiveEvents, AUTO)


PB_BIND(RemoteApiRs232_RinseForced, RemoteApiRs232_RinseForced, AUTO)


PB_BIND(RemoteApiRs232_RinsePostponed, RemoteApiRs232_RinsePostponed, AUTO)


PB_BIND(RemoteApiRs232_SwVersion, RemoteApiRs232_SwVersion, AUTO)


PB_BIND(RemoteApiRs232_ErrorEvent, RemoteApiRs232_ErrorEvent, AUTO)


PB_BIND(RemoteApiRs232_ProductFinished, RemoteApiRs232_ProductFinished, AUTO)


PB_BIND(RemoteApiRs232_ProductAvailabilityChanged, RemoteApiRs232_ProductAvailabilityChanged, AUTO)


PB_BIND(RemoteApiRs232_RinsingUpcoming, RemoteApiRs232_RinsingUpcoming, AUTO)


PB_BIND(RemoteApiRs232_RinseStarted, RemoteApiRs232_RinseStarted, AUTO)


PB_BIND(RemoteApiRs232_UnknownMessage, RemoteApiRs232_UnknownMessage, AUTO)


PB_BIND(RemoteApiRs232_WrongCrc, RemoteApiRs232_WrongCrc, AUTO)


PB_BIND(RemoteApiRs232_BrokenMessage, RemoteApiRs232_BrokenMessage, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

